/* Generated by Antigravity CLI 1.1.22 (Gemini 3.7 Flash (High)) */

/*
<<<<<<< HEAD
 * Copyright (C) 2026 Microsoft / Neverball authors / Ersohn Styne
=======
 * Copyright (C) 2026 Neverball authors
>>>>>>> 36ff995f095995c97e388f87c35c52e6648bfe57
 *
 * NEVERBALL is  free software; you can redistribute  it and/or modify
 * it under the  terms of the GNU General  Public License as published
 * by the Free  Software Foundation; either version 2  of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT  ANY  WARRANTY;  without   even  the  implied  warranty  of
 * MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
 * General Public License for more details.
 */

#include <stdio.h>
#include <string.h>

/*
 * HACK: Used with console version
 */
#include "console_control_gui.h"

#if NB_HAVE_PB_BOTH==1
#include "networking.h"
#include "account.h"
#include "account_wgcl.h"
#include "campaign.h" /* New: Campaign */
#endif

#include "gui.h"
#include "transition.h"
#include "audio.h"
#include "config.h"
#include "common.h"
#include "package.h"
#include "set.h"
#include "progress.h"
#include "lang.h"
#include "log.h"
#include "video.h"
#include "geom.h"
#include "text.h"
#include "strbuf/strbuf.h"
#include "strbuf/substr.h"
#include "strbuf/joinstr.h"

#include "game_client.h"

#include "st_game_link.h"
#include "st_level.h"
#include "st_start.h"
#include "st_title.h"
#include "st_common.h"

#include "st_set.h"

#define AUD_MENU     "snd/menu.ogg"
#define AUD_BACK     "snd/back.ogg"
#define AUD_DISABLED "snd/disabled.ogg"

#define GENERIC_GAMEMENU_ACTION                      \
        if (st_global_animating() ||                 \
            time_state() < 0.1f) {                   \
            if (time_state() < 0.1f)                 \
                log_errorf("Clicking too fast!\n");  \
            audio_play(AUD_DISABLED, 1.0f);          \
            return 1;                                \
        } else audio_play(GUI_BACK == tok ?          \
                          AUD_BACK :                 \
                          (GUI_NONE == tok ?         \
                           AUD_DISABLED : AUD_MENU), \
                          1.0f)

#define GAMEPAD_GAMEMENU_ACTION_SCROLL(tok1, tok2, itemstep) \
        if (st_global_animating() || time_state() < 0.1f) {  \
            if (time_state() < 0.1f)                         \
                log_errorf("Clicking too fast!\n");          \
            audio_play(AUD_DISABLED, 1.0f);                  \
            return 1;                                        \
        } else if (tok == tok1 || tok == tok2) {             \
            if (tok == tok1)                                 \
                audio_play(first > 1 ?                       \
                           AUD_MENU : AUD_DISABLED, 1.0f);   \
            if (tok == tok2)                                 \
                audio_play(first + itemstep < total ?        \
                           AUD_MENU : AUD_DISABLED, 1.0f);   \
        } else GENERIC_GAMEMENU_ACTION

#define KEYBOARD_GAMEMENU_ACTION(tok_enter)            \
        if (st_global_animating() ||                   \
            time_state() < 0.1f) {                     \
            if (time_state() < 0.1f)                   \
                log_errorf("Clicking too fast!\n");    \
            audio_play(AUD_DISABLED, 1.0f);            \
            return 1;                                  \
        } else if (tok == GUI_CHAR || tok == GUI_CL) { \
            audio_play(AUD_2_2_0_KEYBD_CHAR, 1.0f);    \
        } else if (tok == GUI_BS) {                    \
            audio_play(AUD_2_2_0_KEYBD_BS, 1.0f);      \
        } else if (tok == tok_enter) {                 \
            audio_play(AUD_2_2_0_KEYBD_ENTER, 1.0f);   \
        } else GENERIC_GAMEMENU_ACTION

static struct {
    char link[MAXSTR];
    char set_file[MAXSTR];
    char map_part[64];
    int  package_id;
    int  downloading;
    int  status_id;
    char progress_label[MAXSTR];
} game_link_ctx;

/*
 * Launch a level or level set once installed.
 */
static int game_link_launch_target(void)
{
    int index;

    set_init(0);

    if ((index = set_find(game_link_ctx.set_file)) >= 0)
    {
        set_goto(index);

        if (*game_link_ctx.map_part)
        {
            STRBUF sol_basename = str_ends_with(game_link_ctx.map_part, ".sol") ||
                                  str_ends_with(game_link_ctx.map_part, ".solx") ?
                                  strbuf(game_link_ctx.map_part) :
                                  joinstr(game_link_ctx.map_part, ".sol");
            struct level *level = set_find_level(CSTR(sol_basename));

            if (level)
            {
                progress_reinit(MODE_NORMAL);
                if (progress_play(level))
                    return goto_state(&st_level);
            }
            log_errorf("Game Link: level %s not found in set, opening set menu: %s", CSTR(sol_basename), fs_error());
        }

#ifndef SET_ALWAYS_UNLOCKED
        int set_was_unlocked = account_get_d(ACCOUNT_SET_UNLOCKS) > 0 &&
                               (server_policy_get_d(SERVER_POLICY_LEVELGROUP_UNLOCKED_LEVELSET) ||
                                campaign_career_unlocked())
#if NB_STEAM_API == 0 && NB_EOS_SDK == 0
                            || config_cheat()
#endif
            ;

        if (set_was_unlocked)
        {
            load_title_background();
            game_kill_fade();
            return goto_state(&st_start);
        }
        else
        {
            log_errorf("Game Link: Level set is locked due to missing conditions \"game completed\"!");
            return goto_state(&st_start);
        }
#else
        load_title_background();
        game_kill_fade();
        return goto_state(&st_start);
#endif
    }
    return goto_state(&st_title);
}

/*
 * Progress and completion callbacks for package download.
 */
static void game_link_download_progress(void *data1, void *data2)
{
    struct fetch_progress *pr = (struct fetch_progress *) data2;

    if (game_link_ctx.status_id)
    {
        char label[MAXSTR];

        if (pr->total > 0)
        {
            int pct = (int) (pr->now * 100 / pr->total) % 1000;
#if _WIN32 && !defined(__EMSCRIPTEN__) && !_CRT_SECURE_NO_WARNINGS
            sprintf_s(label, MAXSTR, _("Loading (%d%%)..."), pct);
#else
            sprintf(label, _("Loading (%d%%)..."), pct);
#endif
        }
        else
        {
            SAFECPY(label, _("Loading..."));
        }

        if (strcmp(label, game_link_ctx.progress_label) != 0)
        {
            SAFECPY(game_link_ctx.progress_label, label);
            gui_set_label(game_link_ctx.status_id, label);
        }
    }
}

static void game_link_download_done(void *data1, void *data2)
{
    struct fetch_done *dn = (struct fetch_done *) data2;

    game_link_ctx.downloading = 0;

    if (dn && dn->success)
    {
        game_link_launch_target();
    }
    else
    {
        log_errorf("Game Link: download failed for package %d\n", game_link_ctx.package_id);
        goto_state(&st_title);
    }
}

static int game_link_start_download(void)
{
    struct fetch_callback callback = { 0 };

    game_link_ctx.downloading = 1;
    SAFECPY(game_link_ctx.progress_label, _("Loading..."));

    callback.progress = game_link_download_progress;
    callback.done     = game_link_download_done;
    callback.data     = &game_link_ctx;

    if (!package_fetch(game_link_ctx.package_id, callback, 0))
    {
        game_link_download_done(NULL, NULL);
        return 0;
    }

    return 1;
}

static int game_link_action(int tok, int val)
{
    GENERIC_GAMEMENU_ACTION;

    switch (tok)
    {
    case GUI_BACK:
        return exit_state(&st_title);
    }

    return 1;
}

static int game_link_gui(void)
{
    int id;

    if ((id = gui_vstack(0)))
    {
        /* Dimension label box large enough to hold 100% progress. */
        game_link_ctx.status_id = gui_label(id, _("Loading (100%)..."), GUI_SML, GUI_COLOR_WHT);

        gui_layout(id, 0, 0);

        gui_set_label(game_link_ctx.status_id, game_link_ctx.progress_label);
    }

    return id;
}

static int game_link_enter(struct state *st, struct state *prev, int intent)
{
    int id;

    common_init(game_link_action);

    SAFECPY(game_link_ctx.progress_label, _("Loading..."));
    id = game_link_gui();

    game_link_start_download();

    return id;
}

static int game_link_leave(struct state *st, struct state *next, int id, int intent)
{
    gui_delete(id);
    return 0;
}

static void game_link_paint(int id, float st)
{
    gui_paint(id);
}

struct state st_game_link = {
    game_link_enter,
    game_link_leave,
    game_link_paint,
    common_timer,
    common_point,
    common_stick,
    NULL,
    common_click,
    common_keybd,
    common_buttn
};

int game_link_handle(const char *link)
{
    if (!(link && *link))
        return 0;

    log_printf("Game Link: handling %s\n", link);

    if (str_starts_with(link, "set-"))
    {
        const size_t prefix_len = strcspn(link, "/");

        STRBUF set_part = substr(link, 0, prefix_len);
        STRBUF map_part = substr(link, prefix_len + 1, 64);
        STRBUF set_file = str_ends_with(CSTR(set_part), ".txt") ?
                          strbuf(CSTR(set_part)) :
                          joinstr(CSTR(set_part), ".txt");

        SAFECPY(game_link_ctx.link, link);
        SAFECPY(game_link_ctx.set_file, CSTR(set_file));
        SAFECPY(game_link_ctx.map_part, CSTR(map_part));

        /* If already installed, launch immediately. */
        set_init(0);

        if (set_find(CSTR(set_file)) >= 0)
        {
            return game_link_launch_target();
        }

        /* Search available packages */
        int pi = package_search(CSTR(set_file));
        if (pi >= 0)
        {
            game_link_ctx.package_id = pi;
            game_link_ctx.downloading = 0;
            SAFECPY(game_link_ctx.progress_label, _("Loading..."));

            return goto_state(&st_game_link);
        }

        log_errorf("Game Link: set '%s' not found locally or in package catalog\n", CSTR(set_file));
    }

    return 0;
}
