/*
 * Copyright (C) 2025 Microsoft / Neverball authors / Jānis Rūcis
 *
 * NEVERBALL is  free software; you can redistribute  it and/or modify
 * it under the  terms of the GNU General  Public License as published
 * by the Free  Software Foundation; either version 2  of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT  ANY  WARRANTY;  without   even  the  implied  warranty  of
 * MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
 * General Public License for more details.
 */

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

#include <stdio.h>
#include <time.h>

#include "common.h"
#include "fs.h"
#include "text.h"

#include "account_wgcl.h"

#include "config.h"
#include "account.h"

#include "ball.h"

#include "log.h"
#include "parson.h"

#include "state.h"
#include "st_setup.h"
#include "st_wgcl.h"

#if _DEBUG && _MSC_VER
#ifndef _CRTDBG_MAP_ALLOC
#pragma message(__FILE__": Missing _CRT_MAP_ALLOC, recreate: _CRTDBG_MAP_ALLOC + crtdbg.h")
#define _CRTDBG_MAP_ALLOC
#include <crtdbg.h>
#endif
#endif

#if _WIN32 && _MSC_VER
#include <curl/curl.h>

/*
 * HACK: The download code library was auto-generated by Microsoft developer.
 */
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "Crypt32.lib")
#pragma comment(lib, "Normaliz.lib")
#pragma comment(lib, "WS2_32.lib")
#pragma comment(lib, "Wldap32.lib")

#if _DEBUG
#pragma comment(lib, "libcurl_a_debug.lib")
#else
#pragma comment(lib, "libcurl_a.lib")
#endif
#endif

/*---------------------------------------------------------------------------*/

static int curl_is_init;
static int read_only;

static char *session_uuid4;

struct wgcl_res_data
{
    char  *data;
    size_t size;
};

#ifndef __EMSCRIPTEN__
static size_t write_callback(void *buffer, size_t size, size_t nmemb, void *user_data)
{
    size_t realsize = size * nmemb;

    struct wgcl_res_data *res_data = (struct wgcl_res_data *) user_data;

    char *ptr = realloc(res_data->data, res_data->size + realsize + 1);
    if (!ptr)
    {
        log_errorf("WGCL + CURL error: Not enough resources to complete this operation!\n");
        return 0;
    }

    res_data->data = ptr;
    memcpy(&(res_data->data[res_data->size]), buffer, realsize);
    res_data->size += realsize;
    res_data->data[res_data->size] = buffer;

    return realsize;
}
#endif

#if _WIN32 && _MSC_VER && \
    !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
static CURL *account_wgcl_curl_prepare_get(const char *url, void *out_data)
{
#if ENABLE_FETCH!=1
    if (curl_is_init)
    {
        /* Used with ENABLE_FETCH=1 */

        curl_global_cleanup();
        curl_is_init = 0;
    }
#endif

    unsigned long long init_flags = CURL_GLOBAL_NOTHING;

    /* Check if URL contains HTTPS. If so, use SSL init flags. */

    if (str_starts_with(url, "https:"))
        init_flags |= CURL_GLOBAL_SSL;

    /* In Windows 11 and later OS, we'll use Win32. */

    init_flags |= CURL_GLOBAL_WIN32;

#if ENABLE_FETCH!=1
    /* Used with ENABLE_FETCH=1 */

    curl_global_init(init_flags);
    curl_is_init = 1;
#endif

    CURL *handle = curl_easy_init();
    if (!handle)
    {
#if ENABLE_FETCH!=1
        /* Used with ENABLE_FETCH=1 */

        curl_global_cleanup();
        curl_is_init = 0;
#endif
        return 0;
    }

    curl_easy_setopt(handle, CURLOPT_URL,           url);
    curl_easy_setopt(handle, CURLOPT_WRITEFUNCTION, write_callback);
    curl_easy_setopt(handle, CURLOPT_WRITEDATA,     out_data);

#if NB_HAVE_PB_BOTH==1
    curl_easy_setopt(handle, CURLOPT_USERAGENT, "pennyball/" VERSION);
#else
    curl_easy_setopt(handle, CURLOPT_USERAGENT, "neverball/" VERSION);
#endif

    curl_easy_setopt(handle, CURLOPT_ACCEPT_ENCODING, "");

#ifdef CURLSSLOPT_NATIVE_CA
    curl_easy_setopt(handle, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
#endif

    return handle;
}

static CURL *account_wgcl_curl_prepare_post(const char *url, const char *in_json_data, void *out_data)
{
#if ENABLE_FETCH!=1
    if (curl_is_init)
    {
        /* Used with ENABLE_FETCH=1 */

        curl_global_cleanup();
        curl_is_init = 0;
    }
#endif

    unsigned long long init_flags = CURL_GLOBAL_NOTHING;

    /* Check if URL contains HTTPS. If so, use SSL init flags. */

    if (str_starts_with(url, "https:"))
        init_flags |= CURL_GLOBAL_SSL;

    /* In Windows 11 and later OS, we'll use Win32. */

    init_flags |= CURL_GLOBAL_WIN32;

#if ENABLE_FETCH!=1
    /* Used with ENABLE_FETCH=1 */

    curl_global_init(init_flags);
#endif

    CURL *handle = curl_easy_init();
    if (!handle)
    {
#if ENABLE_FETCH!=1
        /* Used with ENABLE_FETCH=1 */

        curl_global_cleanup();
        curl_is_init = 0;
#endif
        return 0;
    }

    struct curl_slist *headers = NULL;
    headers = curl_slist_append(headers, "Content-Type: application/json");

    curl_easy_setopt(handle, CURLOPT_URL,           url);
    curl_easy_setopt(handle, CURLOPT_HTTPHEADER,    headers);
    curl_easy_setopt(handle, CURLOPT_POST,          1l);
    curl_easy_setopt(handle, CURLOPT_POSTFIELDS,    in_json_data);
    curl_easy_setopt(handle, CURLOPT_WRITEFUNCTION, write_callback);
    curl_easy_setopt(handle, CURLOPT_WRITEDATA,     out_data);

#if NB_HAVE_PB_BOTH==1
    curl_easy_setopt(handle, CURLOPT_USERAGENT, "pennyball/" VERSION);
#else
    curl_easy_setopt(handle, CURLOPT_USERAGENT, "neverball/" VERSION);
#endif

    curl_easy_setopt(handle, CURLOPT_ACCEPT_ENCODING, "");

#ifdef CURLSSLOPT_NATIVE_CA
    curl_easy_setopt(handle, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
#endif

    return handle;
}

#define account_wgcl_curl_execute curl_easy_perform

/*
 * FIXME: You should be alternatively use account_wgcl_curl_execute!
 */
static CURLcode account_wgcl_curl_execute_alt(CURL *handle)
{
    return curl_easy_perform(handle);
}

static void account_wgcl_curl_quit(CURL *handle)
{
    curl_easy_cleanup(handle);
#if ENABLE_FETCH!=1
    /* Used with ENABLE_FETCH=1 */

    curl_global_cleanup();
    curl_is_init = 0;
#endif
}
#endif

/*---------------------------------------------------------------------------*/

#define WGCL_URL "pennyball.stynegame.de"

static int managed_buy_is_pending = 0;

static int managed_buy_flags_pending;
static int managed_buy_coins_cost_pending;

static int assets_add_is_pending = 0;

static int pending_add_wallet_coins;
static int pending_add_wallet_gems;
static int pending_add_consumable_hp;
static int pending_add_consumable_doublecash;
static int pending_add_consumable_halfgrav;
static int pending_add_consumable_doublespeed;

static int assets_set_is_pending = 0;

static int pending_set_wallet_coins;
static int pending_set_wallet_gems;
static int pending_set_consumable_hp;
static int pending_set_consumable_doublecash;
static int pending_set_consumable_halfgrav;
static int pending_set_consumable_doublespeed;

static void account_wgcl_visit_browser_login()
{
#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if !defined(__SWITCH__)
#if _WIN32
    system("explorer https://pennyball.stynegame.de/login");
#elif defined(__APPLE__)
    system("open https://pennyball.stynegame.de/login");
#elif defined(__linux__)
    system("x-www-browser https://pennyball.stynegame.de/login");
#endif
#endif
#endif
}

int account_wgcl_init(void)
{
    account_wgcl_quit();

    return account_init();
}

void account_wgcl_quit(void)
{
    read_only = 0;

    if (session_uuid4)
    {
        free(session_uuid4);
        session_uuid4 = NULL;
    }

    account_quit();
}

/*
 * Check whether PB+NB account exists before reload from server.
 */
int account_wgcl_exists(void)
{
    return account_exists();
}

/*
 * Load PB+NB account.
 */
void account_wgcl_load(void)
{
#ifndef __EMSCRIPTEN__
    config_lock_local_username();
    account_init();
    account_load();

    account_set_s(ACCOUNT_PLAYER, config_get_s(CONFIG_PLAYER));

#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__)
    fs_file wgcl_fin;
    if ((wgcl_fin = fs_open_read("pennyball_wgcl.dat")))
    {
        if (session_uuid4 && *session_uuid4)
        {
            free(session_uuid4);
            session_uuid4 = NULL;
        }

        read_line(&session_uuid4, wgcl_fin);
        fs_close(wgcl_fin);
    }
#endif

/*#if NB_HAVE_PB_BOTH==1 && defined(CONFIG_INCLUDES_ACCOUNT) && defined(CONFIG_INCLUDES_MULTIBALLS)
    ball_multi_free();
    ball_multi_init();
#else
    ball_free();
    ball_init();
#endif*/
#endif
}

/*
 * Save PB+NB account.
 */
void account_wgcl_save(void)
{
#ifndef __EMSCRIPTEN__
    account_save();

#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__)
    if (!read_only) return;

    if (session_uuid4 && *session_uuid4)
    {
        fs_file wgcl_fout;
        if ((wgcl_fout = fs_open_write("pennyball_wgcl.dat")))
        {
            fs_write(session_uuid4, text_length(session_uuid4), wgcl_fout);
            fs_close(wgcl_fout);
        }
    }
#endif
#else
    /* Saving player account on web browser is available on database game. */
#endif
}

/*
 * Try to reload from the PB+NB WGCL.
 */
int account_wgcl_reload(void)
{
#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if _WIN32 && _MSC_VER
    if (!(session_uuid4 && *session_uuid4))
        return !game_setup_process();

    /* Read JSON session file using CURL from the server. */

    char in_url[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(in_url, 512,
#else
    sprintf(in_url,
#endif
            "https://%s/api/internal/getsession", WGCL_URL);

    struct wgcl_res_data res_data = {0};
    
    time_t     wgcl_time_now;
    struct tm *wgcl_utc_time;
    char       wgcl_utc_strfmt[40];

    time(&wgcl_time_now);
    wgcl_utc_time = gmtime(&wgcl_time_now);
    sprintf(wgcl_utc_strfmt, "%04d-%02d-%02dT%02d:%02d:%02d.000Z",
            wgcl_utc_time->tm_year + 1900, wgcl_utc_time->tm_mon + 1, wgcl_utc_time->tm_mday,
            wgcl_utc_time->tm_hour, wgcl_utc_time->tm_min, wgcl_utc_time->tm_sec);

    char json_post_data[MAXSTR];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(json_post_data, MAXSTR,
#else
    sprintf(json_post_data,
#endif
            "{"
            "    \"fetch_post_date_iso\":\"%s\","
            "    \"player_uuid4\":\"%s\""
            "}", wgcl_utc_strfmt, session_uuid4);

    CURL *handle = account_wgcl_curl_prepare_post(in_url, json_post_data, &res_data);
    CURLcode res = account_wgcl_curl_execute(handle);

    account_wgcl_curl_quit(handle);
    if (res != CURLE_OK)
    {
        log_errorf("WGCL + CURL error: Get session is not possible, either offline or needs to log in again.\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_reload_fail;
    }

    /* Now, parse JSON! */

    JSON_Value  *root;
    JSON_Object *root_obj;
    JSON_Object *data_session;

    root = json_parse_string(res_data.data);

    if (!root || json_value_get_type(root) != JSONObject)
    {
        log_errorf("WGCL + CURL error: Not an JSON object!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_reload_fail;
    }

    root_obj = json_value_get_object(root);

    if (json_object_get_number(root_obj, "web_return_code") != 200 &&
        json_object_get_number(root_obj, "web_return_code") != 302)
    {
        log_errorf("WGCL + CURL error: Reload failed: %s / %s\n",
                   json_object_get_string(root_obj, "message_text"),
                   json_object_get_string(root_obj, "message_desc"));
        goto account_wgcl_reload_fail;
    }

    if (!json_object_has_value(root_obj, "data_session"))
    {
        log_errorf("WGCL + CURL error: Not an data_session JSON object!\n");
        goto account_wgcl_reload_fail;
    }

    data_session = json_object_get_object(root_obj, "data_session");

#if NB_HAVE_PB_BOTH==1
    if (!json_object_has_value(data_session, "player_uuid4") ||
        !json_object_has_value(data_session, "player_devrole_flags") ||
        !json_object_has_value(data_session, "player_role_flags") ||
        !json_object_has_value(data_session, "player_game_edition_flags") ||
        !json_object_has_value(data_session, "player_firstname") ||
        !json_object_has_value(data_session, "player_lastname") ||
        !json_object_has_value(data_session, "player_name") ||
        !json_object_has_value(data_session, "player_email") ||
        !json_object_has_value(data_session, "player_homepage") ||
        !json_object_has_value(data_session, "player_location") ||
        !json_object_has_value(data_session, "player_exp_current") ||
        !json_object_has_value(data_session, "player_exp_max") ||
        !json_object_has_value(data_session, "player_exp_currentlevel") ||
        !json_object_has_value(data_session, "player_wallet_coins") ||
        !json_object_has_value(data_session, "player_wallet_gems") ||
        !json_object_has_value(data_session, "player_consumable_hp") ||
        !json_object_has_value(data_session, "player_consumable_doublecash") ||
        !json_object_has_value(data_session, "player_consumable_halfgrav") ||
        !json_object_has_value(data_session, "player_consumable_doublespeed"))
#else
    if (!json_object_has_value(data_session, "player_name"))
#endif
    {
        log_errorf("WGCL + CURL error: Session's column values does not matched exactly!\n");
        goto account_wgcl_reload_fail;
    }

    if (!session_uuid4 || strcmp(session_uuid4, json_object_get_string(data_session, "player_uuid4")) != 0)
        account_wgcl_set_session_uuid4(json_object_get_string(data_session, "player_uuid4"));

    char expected_player_name[MAXSTR];
    SAFECPY(expected_player_name, json_object_get_string(data_session, "player_name"));

#if NB_HAVE_PB_BOTH==1
    const int expected_wallet_coins           = ROUND(json_object_get_number(data_session, "player_wallet_coins"));
    const int expected_wallet_gems            = ROUND(json_object_get_number(data_session, "player_wallet_gems"));
    const int expected_consumable_hp          = ROUND(json_object_get_number(data_session, "player_consumable_hp"));
    const int expected_consumable_doublecash  = ROUND(json_object_get_number(data_session, "player_consumable_doublecash"));
    const int expected_consumable_halfgrav    = ROUND(json_object_get_number(data_session, "player_consumable_halfgrav"));
    const int expected_consumable_doublespeed = ROUND(json_object_get_number(data_session, "player_consumable_doublespeed"));
    const int expected_managed_product_flags  = ROUND(json_object_get_number(data_session, "player_managed_product_flags"));

    if (strcmp(config_get_s(CONFIG_PLAYER), expected_player_name) != 0)
    {
        log_errorf("WGCL + CURL error: Client's player name (config_get_s(CONFIG_PLAYER): %s) does not matched by the session's player name (json_object_get_string(data_session, \"player_name\")): %s)\n",
                   config_get_s(CONFIG_PLAYER), expected_player_name);

        account_save();
        config_set_s(CONFIG_PLAYER, expected_player_name);
        account_init();
        account_load();
        account_set_s(ACCOUNT_PLAYER, expected_player_name);
    }

    if (account_get_d(ACCOUNT_DATA_WALLET_COINS) != expected_wallet_coins &&
        expected_wallet_coins >= 0)
        account_set_d(ACCOUNT_DATA_WALLET_COINS, expected_wallet_coins);

    if (account_get_d(ACCOUNT_DATA_WALLET_GEMS) != expected_wallet_gems)
        account_set_d(ACCOUNT_DATA_WALLET_GEMS, expected_wallet_gems);

    if (account_get_d(ACCOUNT_CONSUMEABLE_EXTRALIVES) != expected_consumable_hp &&
        expected_wallet_coins >= -1)
        account_set_d(ACCOUNT_CONSUMEABLE_EXTRALIVES, expected_consumable_hp);

    if (account_get_d(ACCOUNT_CONSUMEABLE_EARNINATOR) != expected_consumable_doublecash &&
        expected_consumable_doublecash >= -1)
        account_set_d(ACCOUNT_CONSUMEABLE_EARNINATOR, expected_consumable_doublecash);

    if (account_get_d(ACCOUNT_CONSUMEABLE_FLOATIFIER) != expected_consumable_halfgrav &&
        expected_consumable_halfgrav >= -1)
        account_set_d(ACCOUNT_CONSUMEABLE_FLOATIFIER, expected_consumable_halfgrav);

    if (account_get_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER) != expected_consumable_doublespeed &&
        expected_consumable_doublespeed >= -1)
        account_set_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER, expected_consumable_doublespeed);

    // Managed product are very trick from integer flags
    // 1 = Extra Levels
    // 2 = Online balls
    // 4 = Bonus packs
    // 8 = Mediation (Zen mode (PB Premium))

    if (account_get_d(ACCOUNT_PRODUCT_LEVELS) != (((expected_managed_product_flags & 1) == 1) ? 1 : 0))
        account_set_d(ACCOUNT_PRODUCT_LEVELS, (((expected_managed_product_flags & 1) == 1) ? 1 : 0));

    if (account_get_d(ACCOUNT_PRODUCT_BALLS) != (((expected_managed_product_flags & 2) == 2) ? 1 : 0))
        account_set_d(ACCOUNT_PRODUCT_BALLS, (((expected_managed_product_flags & 2) == 2) ? 1 : 0));

    if (account_get_d(ACCOUNT_PRODUCT_BONUS) != (((expected_managed_product_flags & 4) == 4) ? 1 : 0))
        account_set_d(ACCOUNT_PRODUCT_BONUS, (((expected_managed_product_flags & 4) == 4) ? 1 : 0));

    if (account_get_d(ACCOUNT_PRODUCT_MEDIATION) != (((expected_managed_product_flags & 8) == 8) ? 1 : 0))
        account_set_d(ACCOUNT_PRODUCT_MEDIATION, (((expected_managed_product_flags & 8) == 8) ? 1 : 0));
#else
    if (strcmp(config_get_s(CONFIG_PLAYER), expected_player_name) != 0)
    {
        log_errorf("WGCL + CURL error: Client's player name (config_get_s(CONFIG_PLAYER): %s) does not matched by the session's player name (json_object_get_string(data_session, \"player_name\")): %s)\n",
                   config_get_s(CONFIG_PLAYER), expected_player_name);

        config_set_s(CONFIG_PLAYER, expected_player_name);
    }
#endif
    read_only = 1;

    free(res_data.data);

#if NB_HAVE_PB_BOTH==1 && defined(CONFIG_INCLUDES_ACCOUNT) && defined(CONFIG_INCLUDES_MULTIBALLS)
    ball_multi_free();
    ball_multi_init();
#else
    ball_free();
    ball_init();
#endif

    log_printf("WGCL + CURL info: Done!\n");
    return 1;

account_wgcl_reload_fail:
    free(res_data.data);
    return 0;

#else
    return 1;
#endif
#elif defined(__EMSCRIPTEN__) && NB_HAVE_PB_BOTH==1
    if (session_uuid4)
    {
        free(session_uuid4);
        session_uuid4 = NULL;
    }

    int r = EM_ASM_INT({
        return Neverball.gamecore_account_try_reload() ? 1 : 0;
    });

    return 1;
#else
    return 0;
#endif
}

void account_wgcl_set_session_uuid4(const char *uuid4)
{
    if (session_uuid4)
    {
        free(session_uuid4);
        session_uuid4 = NULL;
    }

    session_uuid4 = strdup(uuid4);
}

void account_wgcl_set_readonly_playername(const char *f)
{
    read_only = atoi(f);
}

/*
 * Check whether Player name is read only by PB+NB account.
 */
int account_wgcl_name_read_only(void)
{
#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if NB_HAVE_PB_BOTH==1
    return read_only;
#else
    return 0;
#endif
#else
    return 0;
#endif
}

/*
 * Try to sign in to the PB+NB WGCL.
 */
int account_wgcl_login(const char *name, const char *password)
{
#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if _WIN32 && _MSC_VER
    char in_url[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf(in_url, 512,
#else
    sprintf(in_url,
#endif
            "https://%s/api/internal/login", WGCL_URL);

    struct wgcl_res_data res_data = {0};
    
    time_t     wgcl_time_now;
    struct tm *wgcl_utc_time;
    char       wgcl_utc_strfmt[40];

    time(&wgcl_time_now);
    wgcl_utc_time = gmtime(&wgcl_time_now);
    sprintf(wgcl_utc_strfmt, "%04d-%02d-%02dT%02d:%02d:%02d.000Z",
            wgcl_utc_time->tm_year + 1900, wgcl_utc_time->tm_mon + 1, wgcl_utc_time->tm_mday,
            wgcl_utc_time->tm_hour, wgcl_utc_time->tm_min, wgcl_utc_time->tm_sec);

    char json_data[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(json_data, 512
#else
    sprintf(json_data,
#endif
            "{"
            "    \"fetch_post_date_iso\":\"%s\","
            "    \"name\":\"%s\","
            "    \"password\":\"%s\""
            "}",
            wgcl_utc_strfmt, name, password);

    CURL *handle = account_wgcl_curl_prepare_post(in_url, json_data, &res_data);
    CURLcode res = account_wgcl_curl_execute(handle);

    account_wgcl_curl_quit(handle);
    if (res != CURLE_OK)
    {
        log_errorf("WGCL + CURL error: Login is not possible, either offline or needs to log in again.\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_login_fail;
    }

    /* Now, parse JSON! */

    JSON_Value  *root;
    JSON_Object *root_obj;

    root = json_parse_string(res_data.data);

    if (!root || json_value_get_type(root) != JSONObject)
    {
        log_errorf("WGCL + CURL error: Not an JSON object!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_login_fail;
    }

    root_obj = json_value_get_object(root);
    if (!json_object_has_value(root_obj, "web_return_code") ||
        !json_object_has_value(root_obj, "message_text") ||
        !json_object_has_value(root_obj, "message_desc") ||
        !json_object_has_value(root_obj, "session_player_uuid4"))
    {
        log_errorf("WGCL + CURL error: Session's column values does not matched exactly!\n");
        goto account_wgcl_login_fail;
    }

    if (json_object_get_number(root_obj, "web_return_code") != 200 &&
        json_object_get_number(root_obj, "web_return_code") != 302)
    {
        log_errorf("WGCL + CURL error: Login failed: %s / %s\n",
                   json_object_get_string(root_obj, "message_text"),
                   json_object_get_string(root_obj, "message_desc"));
        goto account_wgcl_login_fail;
    }
    else
    {
        read_only = 0;

        account_wgcl_set_session_uuid4(json_object_get_string(root_obj, "session_player_uuid4"));
    }

    free(res_data.data);
    return account_wgcl_reload();

account_wgcl_login_fail:
    free(res_data.data);
    return 0;
#else
    return 1;
#endif
#else
    return 0;
#endif
}

/*
 * Try to logout to the PB+NB WGCL.
 */
int account_wgcl_logout(void)
{
    if (session_uuid4)
    {
        free(session_uuid4);
        session_uuid4 = NULL;
    }

    read_only = 0;

    fs_remove("pennyball_wgcl.dat");
    return 1;
}

int account_wgcl_try_add(int w_coins, int w_gems,
                         int c_hp, int c_doublecash, int c_halfgrav, int c_doublespeed)
{
    if (!(session_uuid4 && *session_uuid4))
        return 1;

    if (!assets_add_is_pending)
    {
        assets_add_is_pending              = 1;
        pending_add_wallet_coins           = w_coins;
        pending_add_wallet_gems            = w_gems;
        pending_add_consumable_hp          = c_hp;
        pending_add_consumable_doublecash  = c_doublecash;
        pending_add_consumable_halfgrav    = c_halfgrav;
        pending_add_consumable_doublespeed = c_doublespeed;
    }

    const int w_coins_curr       = account_get_d(ACCOUNT_DATA_WALLET_COINS);
    const int w_gems_curr        = account_get_d(ACCOUNT_DATA_WALLET_GEMS);
    const int c_hp_curr          = account_get_d(ACCOUNT_CONSUMEABLE_EXTRALIVES);
    const int c_doublecash_curr  = account_get_d(ACCOUNT_CONSUMEABLE_EARNINATOR);
    const int c_halfgrav_curr    = account_get_d(ACCOUNT_CONSUMEABLE_FLOATIFIER);
    const int c_doublespeed_curr = account_get_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER);

    /* HACK: Can also add as negative values. */

    const int w_coins_next       = w_coins_curr       + pending_add_wallet_coins;
    const int w_gems_next        = w_gems_curr        + pending_add_wallet_gems;
    const int c_hp_next          = c_hp_curr          + pending_add_consumable_hp;
    const int c_doublecash_next  = c_doublecash_curr  + pending_add_consumable_doublecash;
    const int c_halfgrav_next    = c_halfgrav_curr    + pending_add_consumable_halfgrav;
    const int c_doublespeed_next = c_doublespeed_curr + pending_add_consumable_doublespeed;

#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if _WIN32 && _MSC_VER
#if NB_HAVE_PB_BOTH==1
    char in_url[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(in_url, 512,
#else
    sprintf(in_url,
#endif
            "https://%s/api/internal/updateassets", WGCL_URL);

    struct wgcl_res_data res_data = {0};

    time_t     wgcl_time_now;
    struct tm *wgcl_utc_time;
    char       wgcl_utc_strfmt[40];

    time(&wgcl_time_now);
    wgcl_utc_time = gmtime(&wgcl_time_now);
    sprintf(wgcl_utc_strfmt, "%04d-%02d-%02dT%02d:%02d:%02d.000Z",
            wgcl_utc_time->tm_year + 1900, wgcl_utc_time->tm_mon + 1, wgcl_utc_time->tm_mday,
            wgcl_utc_time->tm_hour, wgcl_utc_time->tm_min, wgcl_utc_time->tm_sec);

    char json_data[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(json_data, 512,
#else
    sprintf(json_data,
#endif
              "{"
              "    \"fetch_post_date_iso\":\"%s\","
              "    \"player_uuid4\":\"%s\","
              "    \"player_wallet_coins\":%d,"
              "    \"player_wallet_gems\":%d,"
              "    \"player_consumable_hp\":%d,"
              "    \"player_consumable_doublecash\":%d,"
              "    \"player_consumable_halfgrav\":%d,"
              "    \"player_consumable_doublespeed\":%d"
              "}",
              wgcl_utc_strfmt, session_uuid4,
              w_coins_next, w_gems_next,
              c_hp_next, c_doublecash_next, c_halfgrav_next, c_doublespeed_next);

    CURL *handle = account_wgcl_curl_prepare_post(in_url, json_data, &res_data);
    CURLcode res = account_wgcl_curl_execute(handle);

    account_wgcl_curl_quit(handle);
    if (res != CURLE_OK)
    {
        log_errorf("Updating asset value is not possible, either offline or needs to log in again.\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_add_fail;
    }

    /* Now, parse JSON! */

    JSON_Value  *root;
    JSON_Object *root_obj;

    root = json_parse_string(res_data.data);

    if (!root || json_value_get_type(root) != JSONObject)
    {
        log_errorf("WGCL + CURL error: Not an JSON object!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_add_fail;
    }

    root_obj = json_value_get_object(root);
    if (!json_object_has_value(root_obj, "web_return_code") ||
        !json_object_has_value(root_obj, "message_text") ||
        !json_object_has_value(root_obj, "message_desc"))
    {
        log_errorf("WGCL + CURL error: Session's column values does not matched exactly!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_add_fail;
    }
    else if (json_object_get_number(root_obj, "web_return_code") != 200)
    {
        log_errorf("WGCL + CURL error: Update failed: %s / %s\n",
                   json_object_get_string(root_obj, "message_text"),
                   json_object_get_string(root_obj, "message_desc"));

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_add_fail;
    }

    assets_add_is_pending              = 0;
    pending_add_wallet_coins           = 0;
    pending_add_wallet_gems            = 0;
    pending_add_consumable_hp          = 0;
    pending_add_consumable_doublecash  = 0;
    pending_add_consumable_halfgrav    = 0;
    pending_add_consumable_doublespeed = 0;

    free(res_data.data);

    log_printf("WGCL + CURL info: Done!\n");
    return 1;

account_wgcl_try_add_fail:
    free(res_data.data);
    return 0;
#else
    return 1;
#endif
#else
    return 1;
#endif
#elif defined(__EMSCRIPTEN__) && NB_HAVE_PB_BOTH==1
    assets_add_is_pending = 0;

    int r = EM_ASM_INT({
        return Neverball.gamecore_account_try_update(UTF8ToString($0), $1, $2, $3, $4, $5, $6) ? 1 : 0;
    }, session_uuid4,
       w_coins_curr + w_coins, w_gems_curr + w_gems,
       c_hp_curr + c_hp,
       c_doublecash_curr + c_doublecash,
       c_halfgrav_curr + c_halfgrav,
       c_doublespeed_curr + c_doublespeed);

    return 1;
#else
    return 1;
#endif
}

int account_wgcl_try_set(int w_coins, int w_gems,
                         int c_hp, int c_doublecash, int c_halfgrav, int c_doublespeed)
{
    if (!(session_uuid4 && *session_uuid4))
        return 1;

    if (!assets_set_is_pending)
    {
        assets_set_is_pending = 1;
        pending_set_wallet_coins = w_coins;
        pending_set_wallet_gems = w_gems;
        pending_set_consumable_hp = c_hp;
        pending_set_consumable_doublecash = c_doublecash;
        pending_set_consumable_halfgrav = c_halfgrav;
        pending_set_consumable_doublespeed = c_doublespeed;
    }

#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if _WIN32 && _MSC_VER
#if NB_HAVE_PB_BOTH==1
    char in_url[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(in_url, 512,
#else
    sprintf(in_url,
#endif
            "https://%s/api/internal/updateassets", WGCL_URL);

    struct wgcl_res_data res_data = {0};
    
    time_t     wgcl_time_now;
    struct tm *wgcl_utc_time;
    char       wgcl_utc_strfmt[40];

    time(&wgcl_time_now);
    wgcl_utc_time = gmtime(&wgcl_time_now);
    sprintf(wgcl_utc_strfmt, "%04d-%02d-%02dT%02d:%02d:%02d.000Z",
            wgcl_utc_time->tm_year + 1900, wgcl_utc_time->tm_mon + 1, wgcl_utc_time->tm_mday,
            wgcl_utc_time->tm_hour, wgcl_utc_time->tm_min, wgcl_utc_time->tm_sec);

    char json_data[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(json_data, 512,
#else
    sprintf(json_data,
#endif
              "{"
              "    \"fetch_post_date_iso\":\"%s\","
              "    \"player_uuid4\":\"%s\","
              "    \"player_wallet_coins\":%d,"
              "    \"player_wallet_gems\":%d,"
              "    \"player_consumable_hp\":%d,"
              "    \"player_consumable_doublecash\":%d,"
              "    \"player_consumable_halfgrav\":%d,"
              "    \"player_consumable_doublespeed\":%d"
              "}",
              wgcl_utc_strfmt, session_uuid4,
              pending_set_wallet_coins, pending_set_wallet_gems,
              pending_set_consumable_hp, pending_set_consumable_doublecash, pending_set_consumable_halfgrav, pending_set_consumable_doublespeed);

    CURL *handle = account_wgcl_curl_prepare_post(in_url, json_data, &res_data);
    CURLcode res = account_wgcl_curl_execute(handle);

    account_wgcl_curl_quit(handle);
    if (res != CURLE_OK)
    {
        log_errorf("WGCL + CURL error: Updating asset value is not possible, either offline or needs to log in again.\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_set_fail;
    }

    /* Now, parse JSON! */

    JSON_Value  *root;
    JSON_Object *root_obj;

    root = json_parse_string(res_data.data);

    if (!root || json_value_get_type(root) != JSONObject)
    {
        log_errorf("WGCL + CURL error: Not an JSON object!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_set_fail;
    }

    root_obj = json_value_get_object(root);
    if (!json_object_has_value(root_obj, "web_return_code") ||
        !json_object_has_value(root_obj, "message_text") ||
        !json_object_has_value(root_obj, "message_desc"))
    {
        log_errorf("WGCL + CURL error: Session's column values does not matched exactly!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_set_fail;
    }
    else if (json_object_get_number(root_obj, "web_return_code") != 200)
    {
        log_errorf("WGCL + CURL error: Update failed: %s / %s\n",
                   json_object_get_string(root_obj, "message_text"),
                   json_object_get_string(root_obj, "message_desc"));

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_set_fail;
    }

    assets_set_is_pending              = 0;
    pending_set_wallet_coins           = 0;
    pending_set_wallet_gems            = 0;
    pending_set_consumable_hp          = 0;
    pending_set_consumable_doublecash  = 0;
    pending_set_consumable_halfgrav    = 0;
    pending_set_consumable_doublespeed = 0;

    free(res_data.data);

    log_printf("WGCL + CURL info: Done!\n");
    return 1;

account_wgcl_try_set_fail:
    free(res_data.data);
    return 0;
#else
    return 1;
#endif
#else
    return 1;
#endif
#elif defined(__EMSCRIPTEN__) && NB_HAVE_PB_BOTH==1
    assets_set_is_pending = 0;

    int r = EM_ASM_INT({
        return Neverball.gamecore_account_try_update(UTF8ToString($0), $1, $2, $3, $4, $5, $6) ? 1 : 0;
    }, session_uuid4,
       w_coins, w_gems,
       c_hp,
       c_doublecash,
       c_halfgrav,
       c_doublespeed);

    return 1;
#else
    return 1;
#endif
}

int account_wgcl_try_buy(int w_coins_cost, int flags)
{
    if (!(session_uuid4 && *session_uuid4))
        return 1;

    if (!managed_buy_is_pending)
    {
        managed_buy_is_pending = 1;
        managed_buy_coins_cost_pending = w_coins_cost;
        managed_buy_flags_pending = flags;
    }

#if !defined(__NDS__) && !defined(__3DS__) && \
    !defined(__GAMECUBE__) && !defined(__WII__) && !defined(__WIIU__) && \
    !defined(__EMSCRIPTEN__)
#if _WIN32 && _MSC_VER
#if NB_HAVE_PB_BOTH==1
    /* TODO: Buy managed products into online browser from in-game instead. */

    char in_url[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(in_url, 512,
#else
    sprintf(in_url,
#endif
            "https://%s/api/internal/shop/buy", WGCL_URL);

    struct wgcl_res_data res_data = {0};
    
    time_t     wgcl_time_now;
    struct tm *wgcl_utc_time;
    char       wgcl_utc_strfmt[40];

    time(&wgcl_time_now);
    wgcl_utc_time = gmtime(&wgcl_time_now);
    sprintf(wgcl_utc_strfmt, "%04d-%02d-%02dT%02d:%02d:%02d.000Z",
            wgcl_utc_time->tm_year + 1900, wgcl_utc_time->tm_mon + 1, wgcl_utc_time->tm_mday,
            wgcl_utc_time->tm_hour, wgcl_utc_time->tm_min, wgcl_utc_time->tm_sec);

    char json_data[512];
#if !_CRT_SECURE_NO_WARNINGS
    sprintf_s(json_data, 512,
#else
    sprintf(json_data,
#endif
            "{"
            "    \"fetch_post_date_iso\":\"%s\","
            "    \"player_uuid4\":\"%s\","
            "    \"new_product_flags\":%d"
            "}",
            wgcl_utc_strfmt, session_uuid4,
            managed_buy_flags_pending);

    CURL *handle = account_wgcl_curl_prepare_post(in_url, json_data, &res_data);
    CURLcode res = account_wgcl_curl_execute(handle);

    account_wgcl_curl_quit(handle);
    if (res != CURLE_OK)
    {
        log_errorf("WGCL + CURL error: Updating asset value is not possible, either offline or needs to log in again.\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_buy_fail;
    }

    /* Now, parse JSON! */

    JSON_Value  *root;
    JSON_Object *root_obj;

    root = json_parse_string(res_data.data);

    if (!root || json_value_get_type(root) != JSONObject)
    {
        log_errorf("WGCL + CURL error: Not an JSON object!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_buy_fail;
    }

    root_obj = json_value_get_object(root);
    if (!json_object_has_value(root_obj, "web_return_code") ||
        !json_object_has_value(root_obj, "message_text") ||
        !json_object_has_value(root_obj, "message_desc"))
    {
        log_errorf("WGCL + CURL error: Session's column values does not matched exactly!\n");

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_buy_fail;
    }
    else if (json_object_get_number(root_obj, "web_return_code") != 200)
    {
        log_errorf("WGCL + CURL error: Buying failed: %s / %s\n",
                   json_object_get_string(root_obj, "message_text"),
                   json_object_get_string(root_obj, "message_desc"));

        account_wgcl_visit_browser_login();

        goto account_wgcl_try_buy_fail;
    }

    managed_buy_is_pending         = 0;
    managed_buy_flags_pending      = 0;
    managed_buy_coins_cost_pending = 0;

    free(res_data.data);

    log_printf("WGCL + CURL info: Done!\n");
    return 1;

account_wgcl_try_buy_fail:
    free(res_data.data);
    return 0;
#else
    return 1;
#endif
#else
    return 1;
#endif
#elif defined(__EMSCRIPTEN__) && NB_HAVE_PB_BOTH==1
    managed_buy_is_pending = 0;

    int r = EM_ASM_INT({
        return Neverball.gamecore_account_try_buy(UTF8ToString($0), $1) ? 1 : 0;
    }, session_uuid4, managed_buy_flags_pending);

    return 1;
#else
    return 1;
#endif
}

int account_wgcl_restart_attempt(void)
{
#if NB_HAVE_PB_BOTH==1 && defined(__EMSCRIPTEN__)
    const int wgcl_account_sync_done = EM_ASM_INT({
        return tmp_online_session_data != undefined &&
               tmp_online_session_data != null;
    });

    if (!wgcl_account_sync_done) return 1;
#endif

    if (managed_buy_flags_pending)
    {
        if (!account_wgcl_try_buy(0, 0))
            return 0;

        int prev_coins = account_get_d(ACCOUNT_DATA_WALLET_COINS);

        account_set_d(ACCOUNT_DATA_WALLET_COINS, prev_coins - managed_buy_coins_cost_pending);
    }

    if (assets_add_is_pending)
    {
        if (!account_wgcl_try_add(0, 0, 0, 0, 0, 0))
            return 0;
    }

    if (assets_set_is_pending)
    {
        if (!account_wgcl_try_set(0, 0, 0, 0, 0, 0))
            return 0;
    }

    return account_wgcl_reload();
}

void account_wgcl_do_add(int w_coins, int w_gems,
                         int c_hp, int c_doublecash, int c_halfgrav, int c_doublespeed)
{
#if NB_HAVE_PB_BOTH==1 && defined(__EMSCRIPTEN__)
    const int wgcl_account_sync_done = EM_ASM_INT({
        return tmp_online_session_data != undefined &&
               tmp_online_session_data != null;
    });

    if (!wgcl_account_sync_done) return;
#endif

    if (!assets_add_is_pending &&
        (w_coins == 0 && w_gems == 0 &&
         c_hp == 0 && c_doublecash == 0 && c_halfgrav == 0 && c_doublespeed == 0))
        return;

    const int w_coins_curr       = account_get_d(ACCOUNT_DATA_WALLET_COINS);
    const int w_gems_curr        = account_get_d(ACCOUNT_DATA_WALLET_GEMS);
    const int c_hp_curr          = account_get_d(ACCOUNT_CONSUMEABLE_EXTRALIVES);
    const int c_doublecash_curr  = account_get_d(ACCOUNT_CONSUMEABLE_EARNINATOR);
    const int c_halfgrav_curr    = account_get_d(ACCOUNT_CONSUMEABLE_FLOATIFIER);
    const int c_doublespeed_curr = account_get_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER);

    if (read_only)
        if (!account_wgcl_try_add(w_coins, w_gems,
                                  c_hp, c_doublecash, c_halfgrav, c_doublespeed))
        {
            goto_state(&st_wgcl_error_offline);
            return;
        }

    account_set_d(ACCOUNT_DATA_WALLET_COINS,      w_coins_curr       + w_coins);
    account_set_d(ACCOUNT_DATA_WALLET_GEMS,       w_gems_curr        + w_gems);
    account_set_d(ACCOUNT_CONSUMEABLE_EXTRALIVES, c_hp_curr          + c_hp);
    account_set_d(ACCOUNT_CONSUMEABLE_EARNINATOR, c_doublecash_curr  + c_doublecash);
    account_set_d(ACCOUNT_CONSUMEABLE_FLOATIFIER, c_doublespeed_curr + c_halfgrav);
    account_set_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER, c_doublespeed_curr + c_doublespeed);
}

void account_wgcl_do_set(int w_coins, int w_gems,
                         int c_hp, int c_doublecash, int c_halfgrav, int c_doublespeed)
{
#if NB_HAVE_PB_BOTH==1 && defined(__EMSCRIPTEN__)
    const int wgcl_account_sync_done = EM_ASM_INT({
        return tmp_online_session_data != undefined &&
               tmp_online_session_data != null;
    });

    if (!wgcl_account_sync_done) return;
#endif

    if (!assets_add_is_pending &&
        (w_coins       == account_get_d(ACCOUNT_DATA_WALLET_COINS)      &&
         w_gems        == account_get_d(ACCOUNT_DATA_WALLET_GEMS)       &&
         c_hp          == account_get_d(ACCOUNT_CONSUMEABLE_EXTRALIVES) &&
         c_doublecash  == account_get_d(ACCOUNT_CONSUMEABLE_EARNINATOR) &&
         c_halfgrav    == account_get_d(ACCOUNT_CONSUMEABLE_FLOATIFIER) &&
         c_doublespeed == account_get_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER)))
        return;

    if (read_only)
        if (!account_wgcl_try_set(w_coins, w_gems,
                                  c_hp, c_doublecash, c_halfgrav, c_doublespeed))
        {
            goto_state(&st_wgcl_error_offline);
            return;
        }

    account_set_d(ACCOUNT_DATA_WALLET_COINS,      w_coins);
    account_set_d(ACCOUNT_DATA_WALLET_GEMS,       w_gems);
    account_set_d(ACCOUNT_CONSUMEABLE_EXTRALIVES, c_hp);
    account_set_d(ACCOUNT_CONSUMEABLE_EARNINATOR, c_doublecash);
    account_set_d(ACCOUNT_CONSUMEABLE_FLOATIFIER, c_halfgrav);
    account_set_d(ACCOUNT_CONSUMEABLE_SPEEDIFIER, c_doublespeed);
}

int account_wgcl_do_buy(int w_coins_cost, int flags)
{
#if NB_HAVE_PB_BOTH==1 && defined(__EMSCRIPTEN__)
    const int wgcl_account_sync_done = EM_ASM_INT({
        return tmp_online_session_data != undefined &&
               tmp_online_session_data != null;
    });

    if (!wgcl_account_sync_done) return 1;
#endif

    if (!managed_buy_is_pending &&
        (w_coins_cost <= 0 &&
         flags != 1 && flags != 2 && flags != 4 && flags != 8))
        return 0;

    if (read_only)
        if (!account_wgcl_try_buy(w_coins_cost, flags))
        {
            goto_state(&st_wgcl_error_offline);
            return 0;
        }

    int prev_coins = account_get_d(ACCOUNT_DATA_WALLET_COINS);

    account_set_d(ACCOUNT_DATA_WALLET_COINS, prev_coins - w_coins_cost);
    return 1;
}
